"""Render docs/M2_taxonomy.md, the M-2 exit record, from artifacts/faults/*_outcomes.parquet."""

import json
from pathlib import Path

import pandas as pd

from fidnn.inject.sweep import summarise
from fidnn.tables import md as _md

GATE = 0.15  # SPEC §12: Track S share below ~15 % escalates to ResNet-56 before the full sweep


def _load(art: Path) -> tuple[pd.DataFrame, list[dict]]:
    frames, sides = [], []
    for p in sorted(art.glob("*_outcomes.parquet")):
        stem = p.name.replace("_outcomes.parquet", "")
        side = json.loads((art / f"{stem}.json").read_text())
        df = pd.read_parquet(p)
        df["model"], df["precision"], df["seed"] = side["model"], side["precision"], side["seed"]
        frames.append(df)
        sides.append(side)
    if not frames:
        raise FileNotFoundError(f"no *_outcomes.parquet under {art}")
    return pd.concat(frames, ignore_index=True), sides


def write(art: Path, out: Path) -> None:
    all_out, sides = _load(art)
    per_arm = (all_out.groupby(["model", "precision", "mode", "seed", "track"])
               .size().unstack("track", fill_value=0))
    per_arm["track_s_share"] = per_arm.get("S", 0) / per_arm.sum(axis=1)
    per_arm = per_arm.reset_index()
    thesis_arms = per_arm[per_arm.model.isin(["m2", "m3"])]
    worst = thesis_arms.track_s_share.min() if len(thesis_arms) else float("nan")
    verdict = (f"**M-2 gate PASSED.** The lowest Track S share over the M2/M3 arms is "
               f"{worst:.1%}, at or above the ~{GATE:.0%} SPEC §12 requires."
               if worst >= GATE else
               f"**M-2 gate NOT MET.** The lowest Track S share over the M2/M3 arms is "
               f"{worst:.1%}, below the ~{GATE:.0%} of SPEC §12: escalate to ResNet-56 (§4.2) "
               f"before generating the full fault population.")

    labels = (all_out.groupby(["model", "precision", "mode", "label"]).size()
              .unstack("label", fill_value=0))
    shares = labels.div(labels.sum(axis=1), axis=0).reset_index()
    by_stratum = summarise(all_out.assign(mode=all_out["model"] + " " + all_out["mode"]))

    side = sides[0]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(f"""# M-2 — Injection engine and outcome taxonomy

**Milestone:** M-2 (SPEC §12) · **Commit:** `{side['git_commit']}` · **ε:** {side['config']['epsilon']}
· **Probes per injection:** {side['config']['probes_per_injection']} · **Generated:** {side['timestamp']}

Generated by `fidnn inject --report-only` from `{art}/*_outcomes.parquet`; edit the code, not this
file. Tracks are never merged: S = MASKED ∪ DEGRADED, H = SDC ∪ CRASH (§4.3).

## Verdict

{verdict}

## Track share per arm

{_md(per_arm)}

## Outcome distribution (share of probes)

{_md(shares)}

## Per bucket, stratum and budget

{_md(by_stratum)}

## Runs included

{_md(pd.DataFrame([{k: s[k] for k in ('model', 'precision', 'mode', 'seed', 'injections',
                                      'probes', 'track_s_share')} for s in sides]))}
""")
    print(f"[m2] wrote {out}")
